CREATE TABLE Sheet1(Column_1 VARCHAR(10),Column_2 VARCHAR(10));
INSERT INTO Sheet1 (Column_1,Column_2) VALUES 
('Terbaru`db_penggajian`.`tb_user`',''),
('`db_furniture(1)`.`user`',''),
('`db_penggajian`.`tb_gaji`',''),
('`db_penggajian`.`tb_karyawan`',''),
('`db_penggajian`.`tb_pembayaran`',''),
('`db_penggajian`.`tb_pajak`',''),
('`db_penggajian`.`tb_absensi`',''),
('`db_penggajian`.`tb_laporan`',''),
('`2110010412`.`tb_laporan`',''),
('`2110010412`.`tb_instansi`',''),
('',''),
('FavoritTidak ada tabel favorit terbaru.',''),
('',''),
('',''),
('',''),
('',''),
('Baru',''),
('',''),
('',''),
('2110010412',''),
('',''),
('',''),
('2110010412ci4webgis',''),
('',''),
('',''),
('2110010412ci4webgiss',''),
('',''),
('',''),
('21100100412_penggajian',''),
('',''),
('',''),
('aplikasikelas',''),
('',''),
('',''),
('data_sekolah_rev',''),
('',''),
('',''),
(' db',''),
('',''),
('',''),
('',''),
('db_furniture(1)',''),
('',''),
('',''),
('db_laporansiswa',''),
('',''),
('',''),
('db_mhs',''),
('',''),
('',''),
('db_pegawai',''),
('',''),
('',''),
('db_penggajian',''),
('',''),
('',''),
('db_poinsiswa',''),
('',''),
('',''),
('db_siswa',''),
('',''),
('',''),
('db_visual4m',''),
('',''),
('',''),
('elearning',''),
('',''),
('',''),
('information_schema',''),
('',''),
('',''),
('kampus',''),
('',''),
('',''),
('kasir',''),
('',''),
('',''),
('kustomer',''),
('',''),
('',''),
('manajemenbarang',''),
('',''),
('',''),
('mysql',''),
('',''),
('',''),
('pbo2',''),
('',''),
('',''),
('pegawai',''),
('',''),
('',''),
('performance_schema',''),
('',''),
('',''),
('phpmyadmin',''),
('',''),
('',''),
('sidasi',''),
('',''),
('',''),
('test',''),
('',''),
('',''),
('uniska',''),
('',''),
('',''),
('visual4mlat',''),
('',''),
('Panel navigasi',''),
('Panel navigasi',''),
('Server',''),
('Basis data',''),
('Tabel',''),
('Panel navigasiAtur tampilan panel navigasi.',''),
('Tampilkan cabang navigasi databasesdi panel navigasi, timpa cabang database serta selectornya',''),
('Link ke panel utamaMenghubungkan dengan panel utama untuk menyoroti database atau tabel yang saat ini.',''),
('Tampilkan logoTampilkan logo di panel navigasi.',''),
('URL tautan logoArahkan URL untuk logo pada panel navigasi.',''),
('Sasaran tautan logoOpen the linked page in the main window (main) or in a new one (new).','mainnew'),
('Aktifkan penyorotanSorot server yang dikenai kursor.',''),
('Item maksimum di tingkat pertamaJumlah item yang dapat ditampilkan pada setiap halaman dari cabang navigasi.',''),
('Jumlah minimum item yang ditampilkan di kotak tabel filterTentukan jumlah minimum item (tabel, view, routines dan event) untuk menampilkan kotak filter.',''),
('Tabel yang terakhir digunakanJumlah maksimum tabel yang terakhir digunakan; atur 0 untuk menonaktifkannya.',''),
('Tabel favoritJumlah maksimum tabel favorit; atur 0 untuk menonaktifkannya.',''),
('Lebar panel navigasiSetel ke 0 untuk menutup panel navigasi.',''),
('Panel navigasiAtur panel navigasi.',''),
('Item maksimal di cabangJumlah item yang dapat ditampilkan pada setiap halaman dari pohon navigasi.',''),
('Item Group di pohonMengelompokkan barang di cabang navigasi (ditentukan oleh pemisah yang didefinisikan di tab Database dan Tabel di atas).',''),
('Bolehkan perluasan pohon navigasiApakah akan menonaktifkan kemungkinan ekspansi database atau tidak.',''),
('Tampilkan tabel pada cabangApakah akan menampilkan tabel di bawah database di pohon navigasi',''),
('Tampilkan Views dalam bentuk bercabangApakah menampilkan views di bawah database di navigation tree',''),
('Tampilkan Fungsi dalam bentuk bercabangApakah akan menampilkan fungsi di bawah database di navigation tree',''),
('Tampilkan prosedur di percabanganApakah akan menampilkan prosedur di bawah database di pohon navigasi',''),
('Tunjukkan events dalam pohonEntah untuk menampilkan events di bawah database di navigation tree',''),
('Expand single databaseEntah untuk menampilkan events di bawah database di navigation tree secara otomatis.',''),
('ServerOpsi tampilan server.',''),
('Tampilkan pilihan serverTampilkan pilihan server di bagian atas panel navigasi.',''),
('Tampilkan server dalam bentuk daftarTampilkan daftar server dalam bentuk daftar dan bukan tarik-turun.',''),
('Basis dataOpsi tampilan basis data.',''),
('Jumlah minimum database yang ditampilkan di kotak tabel filter',''),
('Pemisah hierarki basis dataString yang memisahkan basis data ke dalam tingkat hierarki yang berbeda.',''),
('TabelOpsi tampilan tabel.',''),
('Target ikon akses cepat','StrukturSQLCariTambahkanJelajahi'),
('Target buat ikon akses cepat kedua','StrukturSQLCariTambahkanJelajahi'),
('Pemisah hierarki tabelString yang memisahkan tabel ke dalam tingkat hierarki yang berbeda.',''),
('Kedalaman hierarki tabel maksimum',''),
('Letakkan berkas disini ',''),
('SQL upload          ( 0 ) x          - ',''),
('Javascript harus diaktifkan lewat point ini!',''),
('',''),
('1. Server:        127.0.0.1 ',''),
('',''),
(' Basis data ',''),
(' SQL ',''),
(' Status ',''),
(' Akun pengguna ',''),
(' Ekspor ',''),
(' Impor ',''),
(' Pengaturan ',''),
(' Replikasi ',''),
(' Variabel ',''),
(' Set Karakter ',''),
(' Mesin ',''),
('',''),
('Konsol ',''),
('Bersihkan ',''),
('Riwayat ',''),
('Opsi ',''),
('Bookmark ',''),
('Men-Debug SQL ',''),
('Tekan Ctrl+Enter untuk menjalankan kueri                                                                Press Enter to execute query ',''),
('SELECT * FROM `user` ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `user` ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `user` ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `user` ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `user` ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `user` ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `user` ',''),
('SELECT * FROM `tb_user` ',''),
('ALTER TABLE `tb_user` DROP `password`; ',''),
('ALTER TABLE `tb_user` DROP `level`; ',''),
('ALTER TABLE `tb_user` DROP `status`; ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `user` ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `tb_user` ',''),
('SELECT * FROM `user` ',''),
('SELECT * FROM `tb_user` ',''),
('ascending ',''),
('descending ',''),
('Order: ',''),
('Men-Debug SQL ',''),
('Jumlah ',''),
('Execution order ',''),
('Time taken ',''),
('Order by: ',''),
('Group queries ',''),
('Ungroup queries ',''),
('Tampilkan                                         Buka                                         Show trace                                         Hide trace                                         Jumlah                                         Time taken ',''),
('Bookmark ',''),
('Segarkan ',''),
('Tambah ',''),
('Tidak ada penanda',''),
('Tambah bookmark ',''),
('Label:                                                                                         Basis data target:                                                                                         Bagikan bookmark                                                        Oke ',''),
('Opsi ',''),
('Kembalikan nilai bawaan ',''),
('Selalu tampilkan pesan kueri ',''),
('Tampilkan riwayat kueri di awal ',''),
('Show current browsing query ',''),
('Execute queries on Enter and insert new line with Shift + Enter. To make this permanent, view settings. ',''),
('Beralih ke tema gelap ',''),
('Tampilkan                                         Buka                                         Kueri ulang                                         Ubah                                         Jelaskan                                         Profil                                         Bookmarks                                         Kueri gagal                                         Basis data :                                                             Waktu eksekusi kueri : ',''),
('phpMyAdmin - Galat',''),
('index.php: Parameter yang hilang: what',''),
('index.php: Parameter yang hilang: export_type','');